name: owl_common
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  android_path_provider: ^0.3.0
  azlistview: ^2.0.0
  common_utils: ^2.1.0
  crypto: ^3.0.3
  dart_date: ^1.3.3
  device_info_plus: ^10.1.0
  dio: ^5.5.0+1
  emoji_picker_flutter: ^2.1.1
  file_picker: ^8.0.0+1
  flutter_app_badger: ^1.5.0
  flutter_cache_manager: ^3.3.1
  flutter_easyloading: ^3.0.5
  flutter_image_compress: ^2.3.0
  flutter_local_notifications: ^17.2.1+2
  flutter_screen_lock: ^9.1.0
  flutter_screenutil: ^5.9.3
  flutter_spinkit: ^5.2.1
  get: ^4.6.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_cropper: ^8.0.1
  image_gallery_saver: ^2.0.3
  image_picker: ^1.1.2
  just_audio: ^0.9.37
  map_launcher: ^3.3.1
  mime: ^1.0.5
  mobile_scanner: ^4.0.1
  open_filex: ^4.4.0
  package_info_plus: ^4.2.0
  path_provider: ^2.1.3
  percent_indicator: ^4.2.3
  permission_handler: ^11.3.1
  record: ^5.1.2
  rxdart: ^0.28.0
  scan: ^1.6.0
  scroll_to_index: ^3.0.1
  shared_preferences: ^2.2.3
  sound_mode: ^3.0.0
  talker_dio_logger: ^4.3.4
  uri_to_file: ^1.0.0
  url_launcher: ^6.3.0
  uuid: ^4.4.2
  vibration: ^1.9.0
  video_compress: ^3.1.2
  video_player: ^2.9.1
  visibility_detector: ^0.4.0+2
  wechat_assets_picker: ^8.6.3
  collection: ^1.18.0
  lpinyin: ^2.0.3
  sprintf: ^7.0.0
  extended_image: ^8.2.1
  pull_to_refresh: ^2.0.0
  lottie: ^3.1.2
  flutter_keyboard_visibility: ^6.0.0
  chewie: ^1.8.0
  firebase_core: ^3.2.0
  owl_im_sdk:
    path: ../owl_im_sdk
  provider: ^6.1.2
  flutter_svg: ^2.0.10+1
  flutter_bitcoin: ^1.0.1
  pointycastle: ^3.9.1
  bip39: ^1.0.6
  convert: ^3.1.1
  json_annotation: ^4.9.0
  encrypt: ^5.0.3
  flutter_animate: ^4.5.0
  web3dart: ^2.7.3
  ellipsized_text: ^1.2.0
  flutter_form_builder: ^9.3.0
  http: ^1.2.2
  flutter_dotenv: ^5.1.0
  pretty_qr_code: ^3.3.0
  screenshot: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.8.0

flutter:
  assets:
    - assets/langs/
    - assets/image/
    - assets/svg/
    - assets/json/
    - assets/webp/
    - assets/anim/
    - assets/audio/
