name: owl_live
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  animate_do: ^3.3.4
  common_utils: ^2.1.0
  device_info_plus: ^10.1.0
  flutter:
    sdk: flutter
  flutter_background: ^1.2.0
  flutter_screenutil: ^5.9.3
  get: ^4.6.6
  livekit_client: ^2.2.2
  lottie: ^3.1.2
  rxdart: ^0.28.0
  sprintf: ^7.0.0
  synchronized: ^3.1.0+1
  uuid: ^4.4.2
  wakelock_plus: ^1.2.1
  just_audio: ^0.9.37
  collection: ^1.18.0
  eva_icons_flutter: ^3.1.0
  flutter_webrtc: ^0.11.5

  owl_common:
    path: ../owl_common
  flutter_openim_sdk: 3.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
